// <auto-generated />
namespace Assignment9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_new_property_track : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_new_property_track));
        
        string IMigrationMetadata.Id
        {
            get { return "201704060318251_added_new_property_track"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
