// <auto-generated />
namespace Assignment9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class with_RE_CLERK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(with_RE_CLERK));
        
        string IMigrationMetadata.Id
        {
            get { return "201704061411227_with_RE_CLERK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
