// <auto-generated />
namespace Assignment9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class with_initial_date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(with_initial_date));
        
        string IMigrationMetadata.Id
        {
            get { return "201704062318041_with_initial_date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
