// <auto-generated />
namespace Assignment9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updated_new_property_in_designModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_new_property_in_designModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201703281958140_updated_new_property_in_designModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
